export const enum StatusZamowienieEnum {
  UTWORZONE = 'UTWORZONE',
  ZAAKCEPTOWANE = 'ZAAKCEPTOWANE',
  WYSLANE = 'WYSLANE',
  ZAPLACONE = 'ZAPLACONE',
  ZREALIZOWANE = 'ZREALIZOWANE',
  ANULOWANE = 'ANULOWANE'
}
